import Head from "next/head";
import styles from "@/styles/Home.module.css";

import { useEffect, useState } from "react";

export default function Home() {
  const [loading, setLoading] = useState<boolean>(true);
  const [menuOpen, setMenuOpen] = useState<boolean>(false);

  useEffect(() => {
    setTimeout(() => {
      setLoading(false);

      let pics = document.querySelectorAll("#hero_image");
      console.log(pics);
      for (let i = 0; i < pics.length; i++) {
        let currPic = pics[i] as HTMLElement;
        currPic.animate(
          {
            opacity: 0.7,
          },
          {
            duration: 1000,
            fill: "forwards",
            delay: 500,
            easing: "ease-in",
          }
        );
        currPic.animate(
          {
            transform: `translateY(calc(10% * (${i} - 2)))`,
          },
          {
            duration: 500,
            fill: "forwards",
            delay: 2000,
            easing: "ease-out",
          }
        );
      }

      let menu = document.getElementById("menu") as HTMLElement;
      menu.animate(
        {
          opacity: 1,
        },
        {
          duration: 500,
          fill: "forwards",
          delay: 2500,
          easing: "ease-in",
        }
      );
    }, 3000);
  }, []);

  const openMenu = () => {
    let menu = document.getElementById("menu") as HTMLElement;
    if (menuOpen) {
      menu.animate(
        {
          transform: "none",
        },
        {
          duration: 300,
          fill: "forwards",
          easing: "ease-in",
        }
      );
      setMenuOpen(false);
      // close menu
    } else {
      menu.animate(
        {
          transform: "rotate(90deg)",
        },
        {
          duration: 300,
          fill: "forwards",
          easing: "ease-in",
        }
      );
      setMenuOpen(true);
      // open menu
    }
  };

  return (
    <>
      <Head>
        <title>got coffee?</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {loading && (
        <section className={styles.loading}>
          <h3>Brewing...</h3>
          <div className={styles.bean_container}>
            <img src="/coffee-bean.png" alt="" className={styles.bean} />
            <img src="/coffee-bean.png" alt="" className={styles.bean} />
            <img src="/coffee-bean.png" alt="" className={styles.bean} />
            <img src="/coffee-bean.png" alt="" className={styles.bean} />
            <img src="/coffee-bean.png" alt="" className={styles.bean} />
          </div>
        </section>
      )}
      <section className={styles.hero}>
        <h1>got coffee?</h1>
        <img
          src="/menu.png"
          alt="menu"
          id="menu"
          className={styles.menu}
          onClick={() => openMenu()}
        />
        <div className={styles.image_container}>
          <img
            src="/tina-guina-obV_LM0KjxY-unsplash.jpg"
            alt=""
            className={styles.hero_image}
            id="hero_image"
          />
          <img
            src="/nathan-dumlao-Y3AqmbmtLQI-unsplash.jpg"
            alt=""
            className={styles.hero_image}
            id="hero_image"
          />
          <img
            src="/empreinte-02O1bXB_fgk-unsplash.jpg"
            alt=""
            className={styles.hero_image}
            id="hero_image"
          />
          <img
            src="/nathan-dumlao-Ic8RmXGyfNc-unsplash.jpg"
            alt=""
            className={styles.hero_image}
            id="hero_image"
          />
          <img
            src="/pariwat-pannium-lKQFFWoCjr8-unsplash.jpg"
            alt=""
            className={styles.hero_image}
            id="hero_image"
          />
        </div>
      </section>
    </>
  );
}

export async function getStaticProps(context: any) {
  return {
    props: {},
  };
}
